services:
  planner-service:
    image: local/planner-service:latest
    container_name: planner-service
    hostname: docker-local
    env_file:
      - env_files/dev/service.env
      - env_files/dev/otel.env
    ports:
      - "10000:10000"
    networks:
      - develop-network

networks:
  develop-network:
    external: true
    name: develop