services:
  planner-service:
    image: local/planner-service:latest
    env_file:
      - env_files/dev/service.env
      - env_files/dev/otel.env
    ports:
      - "10003-10004:10000"
    networks:
      - develop-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      mode: replicated
      replicas: 2

networks:
  develop-network:
    external: true
    name: develop